install.packages("ape")
install.packages("d3r")
install.packages("ergm")
install.packages("ggplot2")
install.packages("jsonlite")
install.packages("dplyr")
install.packages("igraph")
install.packages("lubridate")
install.packages("purrr")
install.packages("RColorBrewer")
install.packages("readr")
install.packages("sand")
install.packages("sqldf")
install.packages("wrapr")
install.packages("tidyverse")

